Issue 117 fix end game screen
Blef-team/blef_ios_app pull request #122
Opened 2022-02-09 18:16 UTC by adrian-golian

Closes #117 
Depends on #121 - RESOLVE IT FIRST

2022-02-09 21:25 UTC, maciej-pomykala requested changes

2022-02-09 21:25 UTC, maciej-pomykala commented on Blef/GameScene.swift
> +        }
Instead of calling moveToStartScene inside of this, we could have another if statement above that deals with the case of the game being finished

2022-02-10 00:10 UTC, adrian-golian commented
(Just rebased onto `develop`)

2022-02-11 20:03 UTC, maciej-pomykala approved these changes

2022-02-11 20:04 UTC, merged